Repository shoaibrayeen/Programmers-Community, pull requests merged in 2019-10, with the labels that each got.

#212 SolutionByChanpreet2.java
  Data Structure/Array Or Vector/Kth Smallest Element/SolutionByChanpreet2.java
Labels: Indented

#227 SolutionByVyomChandra.java
  Basic/Search An Element in Sorted Array/SolutionByVyomChandra.java
Labels: Unindented

#206 Create SolutionByTarun.cpp
  Basic/Implement Power Function/SolutionByTarun.cpp
Labels: Unindented, Working, documentation

#244 Power of two
  Bit Algorithm/Check if A Number is Power of Two/SolutionByRamneek.cpp
  Bit Algorithm/Find Non-Repeated Element/SolutionByRamneek.cpp
Labels: Auto Check Error, Unindented, Working, documentation

#250 SolutionByChanpreet2.java
  Bit Algorithm/Find Non-Repeated Element/SolutionByChanpreet2.java
Labels: Indented, Working

#249 Create SolutionByNidhi.java
  Basic/Search An Element in Sorted Array/SolutionByNidhi.java
Labels: Indented, Working

#246 Create SolutionByNidhi.java
  Data Structure/Array Or Vector/Right Rotate An Array By K Elements/SolutionByNidhi.java
Labels: Indented, Optimize it, Working

#245 SolutionByJagmeet
  Data Structure/Array Or Vector/Sort An Array of 0s and 1s/SolutionByJagmeet.py
Labels: Optimize it, Unindented, Working

#242 SolutionByJagmeet.py
  Data Structure/Array Or Vector/Sort An Array of 0s , 1s and 2s/SolutionByJagmeet.py
Labels: Documentation Needed, Unindented, Working

#226 SolutionByVyomChandra.java
  Basic/Reverse A String/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#225 SolutionByVyomChandra.java
  Basic/Convert Decimal To Binary/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#228 SolutionByVyomChandra.java
  Basic/Search An Element in Unsorted Array/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#217 kth smallest element python
  Data Structure/Array Or Vector/Kth Smallest Element/solutionbynaman.py
  Data Structure/Matrix/Print A Given Matrix in Spiral Form/solutionbyNaman.py
Labels: Documentation Needed, Working

#248 Create SolutionByNidhi.java
  Basic/Calculate Nth Fibonacci Number/SolutionByNidhi.java
Labels: Indented, Working

#256 Create SolutionByKaran.java
  Basic/Check if A String is Palindrome or Not/SolutionByKaran.java
Labels: Documentation Needed, Indented, Working

#151 Create SolutionByKaran.cpp
  Basic/Search An Element in Unsorted Array/SolutionByKaran.cpp
Labels: Documentation Needed, Working

#251 Create SolutionByNidhi.java
  Data Structure/Array Or Vector/Move All Zeros to The End of The Array/SolutionByNidhi.java
Labels: Indented, Working

#241 Create SolutionByKaran.cpp
  Basic/Calculate Nth Fibonacci Number/SolutionByKaran.cpp
Labels: Documentation Needed, Working

#252 Create solutionbyRISHABH_B.cpp
  Basic/Calculate Factorial of A Number/solutionbyRISHABH_B.cpp
Labels: Documentation Needed, Unindented, Working

#243 Create SolutionByKaran.cpp
  Basic/Calculate Factorial of A Number/SolutionByKaran.cpp
Labels: Documentation Needed, Unindented, Working

#260 Create SolutionByDeepika.cpp
  Basic/Calculate Nth Fibonacci Number/SolutionByDeepika.cpp
Labels: Documentation Needed, Unindented, Working

#262 Added a solution
  Basic/Convert Decimal To Binary/SolutionbyShailza.java
Labels: Documentation Needed, Unindented, Working

#266 Create SolutionByPiyush.cpp
  Basic/Calculate Factorial of A Number/SolutionByPiyush.cpp
Labels: Unindented, Working

#268 Create SolutionByKaran.cpp
  Bit Algorithm/Check if A Number is Power of Two/SolutionByKaran.cpp
Labels: Documentation Needed, Unindented, Working

#272 Dream achiever
  Basic/Check if A String is Palindrome or Not/SolutionByRishabhSethia.py
Labels: Documentation Needed, Working

#132 solutionByAshutosh.py
  Basic/Reverse A String/solutionByAshutosh.py
Labels: Documentation Needed, Working

#270 Create solutionbyRISHABHBANSAL.cpp
  Basic/Search An Element in Sorted Array/solutionbyRISHABHBANSAL.cpp
Labels: Documentation Needed, Optimize it, Unindented, Working

#273 Create SolutionByKaran.cpp
  Basic/Check if A Number is Prime or Not/SolutionByKaran.cpp
Labels: Documentation Needed, Unindented, Working

#274 SolutionByVyomChandra.java
  Basic/Check if A Number is Prime or Not/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#280 Create SolutionByAbhishek.py
  Basic/Reverse A String/SolutionByAbhishek.py
Labels: Documentation Needed, Working

#286 Create SolutonbyBharat1.py
  Bit Algorithm/Find Non-Repeated Element/SolutionbyBharat1.py
Labels: Documentation Needed, Working

#288 solutionbyPrince.cpp
  Basic/Calculate Factorial of A Number/solutionbyprince.cpp
Labels: Documentation Needed, Unindented, Working

#290 Create SolutionbyBharat.py
  Data Structure/Array Or Vector/Find the Missing Number/SolutionbyBharat.py
Labels: Documentation Needed, Working

#291 SolutionByJaskirat.cpp
  Basic/Calculate Factorial of A Number/SolutionByJaskirat.cpp
Labels: Documentation Needed, Unindented, Working

#279 Create SolutionByKaran.cpp
  Data Structure/Array Or Vector/Median of An Unsorted Array/SolutionByKaran.cpp
Labels: Documentation Needed, Unindented, Working

#276 SolutionByVyomChandra.java
  Data Structure/Array Or Vector/Median of An Unsorted Array/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#133 solutionByAshutosh.py
  Basic/Search An Element in Sorted Array/solutionByAshutosh.py
Labels: Documentation Needed, Working

#271 Create SolutionByKaran.cpp
  Basic/Reverse A String/SolutionByKaran.cpp
Labels: Documentation Needed, Unindented, Working

#287 solutionByPrince.cpp
  Data Structure/Array Or Vector/Move All Zeros to The End of The Array/solutionByPrince.cpp
Labels: Documentation Needed, Unindented, Working

#293 SolutionByVyomChandra.java
  Basic/Count Number of Digits in An Integer/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#294 SolutionByVyomChandra.java
  Basic/Display Factors of A Number/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#295 SolutionByRishabh.java
  Basic/Check if A Number is Prime or Not/SolutionByRishabh.java
Labels: Documentation Needed, Unindented, Working

#296 SolutionByRishabh.java
  Basic/Calculate Factorial of A Number/SolutionByRishabh.java
Labels: Documentation Needed, Unindented, Working

#298 SolutionByChanpreet.java
  Data Structure/Array Or Vector/Median of An Unsorted Array/SolutionByChanpreet.java
Labels: Documentation Needed, Working

#299 SolutionByPrabhakar.c
  Basic/Count Number of Digits in An Integer/SolutionByPrabhakar.c
Labels: Documentation Needed, Unindented, Working

#300 SolutionByPrabhakar.c
  Basic/Calculate Factorial of A Number/SolutionByPrabhakar.c
Labels: Documentation Needed, Unindented, Working

#305 solutionByPrince.cpp
  Basic/Count Number of Digits in An Integer/solutionByPrince.cpp
Labels: Documentation Needed, Working

#307 Create SolutionByKaran.cpp
  Basic/Display Factors of A Number/SolutionByKaran.cpp
Labels: Documentation Needed, Working

#308 Create SolutionByKaran
  Basic/Find LCM of Two Numbers/SolutionByKaran.cpp
Labels: Documentation Needed, Working

#284 Next Greater Element!
  Data Structure/Array Or Vector/Next Greater Element/SolutionbyBharat.cpp
Labels: Documentation Needed, Working

#304 SolutionByVyomChandra.java
  Basic/Find GCD of Two Numbers/SolutionByVyomChandra.java
Labels: Documentation Needed, Unindented, Working

#312 Create SolutionByAayush.cpp
  Basic/Find LCM of Two Numbers/SolutionByAayush.cpp
Labels: Documentation Needed, Working

#317 SolutionByPrabhakar.c
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByPrabhakar.c
Labels: Documentation Needed, Unindented, Working

#321 SolutionByAnkit.py
  Basic/Find GCD of Two Numbers/SolutionByAnkit.py
Labels: Documentation Needed, Working

#322 SolutionByAnkit.py
  Basic/Find LCM of Two Numbers/SolutionByAnkit.py
Labels: Documentation Needed, Working

#323 SolutionByAnkit.py
  Basic/Check Whether a Number is Even or Odd/SolutionByAnkit.py
Labels: Working

#324 SolutionByAnkit.py
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByAnkit.py
Labels: Working

#325 Create SolutionBySukriti.java
  Basic/Calculate Factorial of A Number/SolutionBySukriti.java
Labels: Documentation Needed, Unindented, Working

#327 Create SolutionBySukriti.java
  Basic/Count Number of Digits in An Integer/SolutionBySukriti.java
Labels: Documentation Needed, Unindented, Working

#328 Create SolutionBySukriti.java
  Data Structure/Array Or Vector/Sort An Array of 0s , 1s and 2s/SolutionBySukriti.java
Labels: Documentation Needed, Unindented, Working

#329 Create SolutionBySukriti.java
  Bit Algorithm/Find Non-Repeated Element/SolutionBySukriti.java
Labels: Documentation Needed, Unindented, Working

#330 Create SolutionByNidhi.java
  Basic/Check if A Number is Prime or Not/SolutionByNidhi.java
Labels: Indented, Working

#331 Create SolutionByNidhi.java
  Basic/Find GCD of Two Numbers/SolutionByNidhi.java
Labels: Indented, Working

#335 Update readMe.md
  readMe.md
Labels: HacktoberFest

#336 Update readMe.md
  readMe.md
Labels: HacktoberFest

#337 SolutionByRishabh.py
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByRishabh.py
Labels: HacktoberFest, Working

#282 Create SolutionByPradumn.cpp
  Bit Algorithm/Check if A Number is Power of Two/SolutionByPradumn.cpp
Labels: Documentation Needed, Unindented, Working

#350 Create SolutionByMananpreet.java
  Basic/Calculate Factorial of A Number/SolutionByMananpreet.java
Labels: Documentation Needed, Working

#352 Create SolutionByMananpreet.java
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByMananpreet.java
Labels: Working

#353 Create SolutionBySimar.c
  Data Structure/Matrix/Print A Given Matrix in Spiral Form/SolutionBySimar.c
Labels: Documentation Needed, Working

#355 Create SolutionBySimar.py
  Dynamic Programming/0-1 Knapsack Problem/SolutionBySimar.py
Labels: Documentation Needed, Working

#356 Create SolutionBySimar.py
  Dynamic Programming/Coin Change/SolutionBySimar.py
Labels: Documentation Needed, Working

#359 Create SolutionByKaran.java
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByKaran.java
Labels: Working

#360 SolutionByPradumn.cpp
  Basic/Count Number of Digits in An Integer/SolutionByPradumn.cpp
Labels: Working

#361 Create SolutionByKaran.cpp
  Basic/Check Whether a Number is Even or Odd/SolutionByKaran.cpp
Labels: Working

#362 Create SolutionByMananpreet.java
  Basic/Check Whether a Number is Even or Odd/SolutionByMananpreet.java
Labels: Working

#366 SolutionByChanpreet.java
  Data Structure/Linked List/Detect Loop in Singly Linked List/SolutionByChanpreet.java
Labels: Working

#367 SolutionByChanpreet2.java
  Data Structure/Linked List/Detect Loop in Singly Linked List/SolutionByChanpreet2.java
Labels: Working

#372 SolutionByPrabhakar.cpp
  Basic/Check Whether a Number is Even or Odd/SolutionByPrabhakar.cpp
Labels: Documentation Needed, Unindented, Working

#373 SolutionByPrabhakar.cpp
  Bit Algorithm/Check if Two Integers Have Opposite Signs/SolutionByPrabhakar.cpp
Labels: Documentation Needed, Unindented, Working

#374 Create SolutionByNidhi.java
  Basic/Count Number of Digits in An Integer/SolutionByNidhi.java
Labels: Indented, Working

#289 Create SolutionbyBharat.cpp
  Data Structure/Linked List/Detect Loop in Singly Linked List/SolutionbyBharat.cpp
Labels: Documentation Needed, Unindented, Working

#376 Solution for reverse a single linked list
  Data Structure/Linked List/Reverse A Singly Linked List/solutionByNeil.cpp
Labels: Working

#380 solutionbygargprince1702.cpp
  Basic/Check if A String is Palindrome or Not/solutionbygargprince1702.cpp
Labels: Working

#381 SolutionByChanpreet.java
  Bit Algorithm/Check if Two Integers Have Opposite Signs/SolutionByChanpreet.java
Labels: Working

#382 Create SolutionByKaran.java
  Bit Algorithm/Check if Two Integers Have Opposite Signs/SolutionByKaran.java
Labels: Working

#383 zigZagarray.cpp
  Data Structure/Array Or Vector/Convert Array into Zig-Zag Fashion/solutionbysakshi.cpp
Labels: Working

#343 Create SolutionByPushpneet.cpp
  Data Structure/Array Or Vector/Find the Missing Number/SolutionByPushpneet.cpp
Labels: Working

#340 Create SolutionByPushpneet.cpp
  Data Structure/Array Or Vector/Next Greater Element/SolutionByPushpneet.cpp
Labels: Working

#339 Create solutionByAman.cpp
  Dynamic Programming/Coin Change/solutionByAman.cpp
Labels: Working

#338 Create SolutionByPradumn.cpp
  Basic/Calculate Factorial of A Number/SolutionByPradumn.cpp
Labels: Documentation Needed, Unindented, Working

#319 SolutionByAnkit.py
  Basic/Count Number of Digits in An Integer/SolutionByAnkit.py
Labels: Working

#318 Create SolutionByAnkit.py
  Basic/Calculate Factorial of A Number/SolutionByAnkit.py
Labels: Documentation Needed, Working

#309 SolutionByDhruv.cpp
  Basic/Count Number of Digits in An Integer/SolutionByDhruv.cpp
Labels: Working

#297 solutionbyIshaan.py
  Basic/Reverse A String/solutionByIshaan.py
Labels: Documentation Needed, Working

#283 Factorial - Solution By Ramneek
  Basic/Calculate Factorial of A Number/SolutionByRamneek.cpp
  Basic/Calculate Nth Fibonacci Number/SolutionByRamneek.cpp
  Basic/Convert Binary to Decimal/SolutionByRamneek.cpp
  Basic/Implement Power Function/SolutionByRamneek.cpp
Labels: Documentation Needed, Unindented, Working

#278 Create SolutionByNidhi.java
  Data Structure/Linked List/Reverse A Singly Linked List/SolutionByNidhi.java
Labels: Indented, Working

#269 Create SolutionByPiyush.cpp
  Basic/Calculate Nth Fibonacci Number/SolutionByPiyush.cpp
Labels: Documentation Needed, Unindented, Working

#357 Solution to Knapsack Problem
  Dynamic Programming/0-1 Knapsack Problem/SolutionByYash.java
Labels: Indented, Working

#378 solutionbygargprince1702.cpp
  Basic/Search An Element in Unsorted Array/solutionbygargprince1702.cpp
Labels: Working

#386 Odd even branch
  Basic/Check Whether a Number is Even or Odd/SolutionBySweta.java
Labels: Working

#388 Branch bit algorithm
  Bit Algorithm/Check if Two Integers Have Opposite Signs/SolutionBySweta.cpp
Labels: Working

#389 Create SolutionByPiyush.cpp
  Data Structure/Array Or Vector/Convert Array into Zig-Zag Fashion/SolutionByPiyush.cpp
Labels: Working

#393 Creating SolutionByAkshat.cpp
  Bit Algorithm/Check if A Number is Power of Two/SolutionByAkshat.cpp
Labels: Working

#394 Create SolutionByMananpreet.java
  Basic/Calculate Nth Fibonacci Number/SolutionByMananpreet.java
Labels: Working

#402 Create SolutionByMananpreet.java
  Basic/Check if A Number is Prime or Not/SolutionByMananpreet.java
Labels: Working

#403 Create SolutionByMananpreet.java
  Basic/Convert Decimal To Binary/SolutionByMananpreet.java
Labels: Working

#405 Create SolutionByEnthusiastDeveloper.py
  Basic/Calculate Factorial of A Number/SolutionByEnthusiastDeveloper.py
Labels: Wrong Output

#406 Create SolutionByEnthusiastDeveloper.py
  Basic/Check if A Number is Prime or Not/SolutionByEnthusiastDeveloper.py
Labels: Working

#407 Create SolutionByNidhi.java
  Basic/Reverse A String/SolutionByNidhi.java
Labels: Working

#408 Create SolutionByNidhi.java
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByNidhi.java
Labels: Working

#409 Create SolutionByNidhi.java
  Data Structure/Array Or Vector/Sort An Array of 0s and 1s/SolutionByNidhi.java
Labels: Working

#414 Create SolutionByNidhi.java
  Basic/Find LCM of Two Numbers/SolutionByNidhi.java
Labels: Working

#415 Create SolutionByNidhi.java
  Basic/Check Whether a Number is Even or Odd/SolutionByNidhi.java
Labels: Working

#416 Create SolutionByNidhi.java
  Basic/Display Factors of A Number/SolutionByNidhi.java
Labels: Working

#417 Create SolutionByNidhi.java
  Basic/Search An Element in Unsorted Array/SolutionByNidhi.java
Labels: Working

#418 Create SolutionByNidhi.java
  Basic/Convert Binary to Decimal/SolutionByNidhi.java
Labels: Working

#420 Solution to check if two integers have opposite signs
  Bit Algorithm/Check if Two Integers Have Opposite Signs/SolutionByVaibhavSethia.py
Labels: Working

#419 Create SolutionByNidhi.java
  Basic/Convert Decimal To Binary/SolutionByNidhi.java
Labels: Working

#421 Solution to find non-repeated element
  Bit Algorithm/Find Non-Repeated Element/SolutionByVaibhavSethia.py
Labels: Working

#423 Create SolutionByEnthusiastDeveloper.py
  Data Structure/Array Or Vector/Sort An Array of 0s and 1s/SolutionByEnthusiastDeveloper.py
Labels: Working

#428 Create SolutionByPranavGurditta.java
  Data Structure/Matrix/Print A Given Matrix in Spiral Form/SolutionByPranavGurditta.java
Labels: Unindented

#200 SolutionByBhavnoor.py
  Basic/Reverse A String/SolutionByBhavnoor.py
Labels: Indented, Working

#210 Create SolutionByMananpreet.java
  Basic/Implement Power Function/SolutionByMananpreet.java
Labels: Indented, Working

#498 Create SolutionByMansi.cpp
  Basic/Calculate Nth Fibonacci Number/SolutionByMansi.cpp
Labels: Wrong Output
