Repository shoaibrayeen/Programmers-Community, pull requests merged in 2020-10, with the labels that each got.

#1254 Stolen Values Problem - readMe
  Dynamic Programming/Stolen Values Problem/readMe.md
Labels: hacktoberfest-accepted

#1196 SolutionBySatwika.java
  Divide and Conquer/K-th Element of Two Sorted Arrays/SolutionBySatwika.java
Labels: hacktoberfest-accepted

#1262 Multiplayer_FruitNinja - Idea Pushed by Piyush Khurana
  docs/Project Ideas/Multiplayer_FruitNinja.md
Labels: hacktoberfest-accepted

#1208 Power Set in Lexicographic Order - readMe
  Backtracking/Power Set in Lexicographic Order/readMe.md
Labels: hacktoberfest-accepted

#1207 Remove Invalid Parentheses - readMe
  Backtracking/Remove Invalid Parentheses/readMe.md
Labels: hacktoberfest-accepted

#1175 Find Closest Number in Array - readMe
  Divide and Conquer/Find Closest Number in Array/readMe.md
Labels: hacktoberfest-accepted

#1209 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Reverse Level Order Traversal/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1256 SolutionByAquib.py
  Basic/Check Leap Year/SolutionByAquib.py
Labels: hacktoberfest-accepted

#1222 Added Java solution
  Data Structure/Binary Tree/Sum of All Left Leaves/SolutionByDhanam.java
Labels: hacktoberfest-accepted

#1218 Added solution in C programming language
  Basic/Calculate Factorial of A Number/SolutionBySushruth.c
Labels: hacktoberfest-accepted

#1213 Added solution to bit algorithm
  Bit Algorithm/Check if A Number is Power of Two/SolutionByAshutosh.cpp
  Greedy Algorithms/Minimum number of Coins/SolutionByAshutosh.cpp
Labels: hacktoberfest-accepted

#1212 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Maximum Value in A Binary Tree/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1255 Minimum Number of Jumps to Reach End - readMe
  Dynamic Programming/Minimum Number of Jumps to Reach End/readMe.md
Labels: hacktoberfest-accepted

#1252 Painting Fence Algorithm - readMe
  Dynamic Programming/Painting Fence Algorithm/readMe.md
Labels: hacktoberfest-accepted

#1251 Palindrome Partitioning - readMe
  Dynamic Programming/Palindrome Partitioning/readMe.md
Labels: hacktoberfest-accepted

#1253 Perfect Sum Problem - readMe
  Dynamic Programming/Perfect Sum Problem/readMe.md
Labels: hacktoberfest-accepted

#1249 Ugly Numbers - readme
  Dynamic Programming/Ugly Numbers/readMe.md
Labels: hacktoberfest-accepted

#1176 Find a Fixed Point in a Given Array - readMe
  Divide and Conquer/Find a Fixed Point in a Given Array/readMe.md
Labels: hacktoberfest-accepted

#1177 Find The Element That Appears Once in A Sorted Array - readMe
  Divide and Conquer/Find The Element That Appears Once in A Sorted Array/readMe.md
Labels: hacktoberfest-accepted

#1180 Create SolutionBySumitSoni.cpp
  Data Structure/Array Or Vector/Search An Element in Unsorted Array/SolutionBySumitSoni.cpp
Labels: hacktoberfest-accepted

#1183 Create SolutionByFuzail.cpp
  Data Structure/Array Or Vector/Subarray with 0 Sum/SolutionByFuzail.cpp
Labels: hacktoberfest-accepted

#1190 Decimal To Binary
  Basic/Check if A Number is Prime or Not/SolutionByIndra.cpp
  Basic/Convert Decimal To Binary/SolutionByIndra.java
  Basic/Find GCD of Two Numbers/SolutionByIndra.java
Labels: hacktoberfest-accepted

#1261 SolutionByAquib.py
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByAquib.py
Labels: hacktoberfest-accepted

#1210 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Diameter of Binary Tree/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1227 SolutionByPrabsimar.cpp
  Basic/Check Leap Year/SolutionByPrabsimar.cpp
Labels: hacktoberfest-accepted

#1226 SolutionByBavleen.cpp
  Basic/Check Leap Year/SolutionByBavleen.cpp
Labels: hacktoberfest-accepted

#1224 SolutionBySumit.c
  Greedy Algorithms/Minimum number of Coins/SolutionBySumit.C
Labels: hacktoberfest-accepted

#1211 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Minimum Value in A Binary Tree/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1221 Added Wildcard Matching Problem
  Dynamic Programming/Wildcard Pattern Matching/SolutionByRishi.java
  Dynamic Programming/Wildcard Pattern Matching/readMe.md
Labels: hacktoberfest-accepted

#1259 Product of digits in a Number >> SolutionByAkshatJain.py -- Hacktoberfest
  Basic/Product of Digits in A Number/SolutionByAkshatJain.py
Labels: hacktoberfest-accepted

#1247 Optimal Strategy for a Game - readMe
  Dynamic Programming/Optimal Strategy for a Game/readMe.md
Labels: hacktoberfest-accepted

#1230 SolutionByPrabsimar.cpp
  Basic/Find GCD of Two Numbers/SolutionByPrabsimar.cpp
Labels: hacktoberfest-accepted

#1235 SolutionByPrabsimar.cpp
  Basic/Compute Length of A String/SolutionByPrabsimar.cpp
Labels: hacktoberfest-accepted

#1233 SolutionByBavleen.cpp
  Basic/Compute Length of A String/SolutionByBavleen.cpp
Labels: hacktoberfest-accepted

#1304 Create Web-Scraper.md
  docs/Project Ideas/Web-Scraper.md
Labels: hacktoberfest-accepted

#1237 SolutionByPrabsimar.cpp
  Basic/Sum of Digits in A Number/SolutionByPrabsimar.cpp
Labels: hacktoberfest-accepted

#1236 SolutionByBavleen.cpp
  Basic/Sum of Digits in A Number/SolutionByBavleen.cpp
Labels: hacktoberfest-accepted

#1228 SolutionByBavleen.cpp
  Basic/Find GCD of Two Numbers/SolutionByBavleen.cpp
Labels: hacktoberfest-accepted

#1197 Coin-Change Problem
  Dynamic Programming/Coin Change/SolutionByKuljeet.cpp
Labels: hacktoberfest-accepted

#1193 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Kth Ancestor of A Node/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1202 Longest Common Prefix - readMe
  Divide and Conquer/Longest Common Prefix/readMe.md
Labels: hacktoberfest-accepted

#1203 Hamiltonian Cycle - readMe
  Backtracking/Hamiltonian Cycle/readMe.md
Labels: hacktoberfest-accepted

#1204 Combinational Sum - readMe
  Backtracking/Combinational Sum/readMe.md
Labels: hacktoberfest-accepted

#1206 Minimum Number of Jumps to Reach ( M , N ) From ( 1 , 1 ) - readMe
  Backtracking/Minimum Number of Jumps to Reach ( M , N ) From ( 1 , 1 )/readMe.md
Labels: hacktoberfest-accepted

#1205 Graph Coloring Problem - readMe
  Backtracking/Graph Coloring Problem/readMe.md
Labels: hacktoberfest-accepted

#1240 Create SolutionByTanmay.cpp
  Bit Algorithm/Find Two Non-Repeating Elements/SolutionByTanmay.cpp
Labels: hacktoberfest-accepted

#1241 Create SolutionbyAastha.Java
  Data Structure/Array Or Vector/Selection Sort/SolutionbyAastha.Java
Labels: hacktoberfest-accepted

#1242 added my solution
  Basic/Calculate Factorial of A Number/SolutionByManan.py
  Basic/Check Whether a Character is Vowel or Consonant/SolutionByManan.py
Labels: hacktoberfest-accepted

#1244 String Reversal >> SolutionByAkshatJain.cpp--Hacktoberfest
  Basic/Reverse A String/SolutionByAkshatJain.cpp
Labels: hacktoberfest-accepted

#1245 Sort A Stack >> SolutionByAkshatJain.cpp -- Hacktoberfest
  Data Structure/Stack/Sort a Stack/SolutionByAkshatJain.cpp
  Data Structure/Stack/Sort a Stack/readMe.md
Labels: hacktoberfest-accepted

#1246 Weighted Job Scheduling - readMe
  Dynamic Programming/Weighted Job Scheduling/readMe.md
Labels: hacktoberfest-accepted

#1248 Temple Offerings - readMe
  Dynamic Programming/Temple Offerings/readMe.md
Labels: hacktoberfest-accepted

#1250 Parenthesis Checker >> SolutionByAkshatJain.cpp -- Hacktoberfest
  Data Structure/Stack/Parenthesis Checker/SolutionByAkshatJain.cpp
  Data Structure/Stack/Parenthesis Checker/readMe.md
Labels: hacktoberfest-accepted

#1257 SolutionByAquib.py
  Basic/Check if A Number is Prime or Not/SolutionByAquib.py
Labels: hacktoberfest-accepted

#1269 computing sum of digits of the number using mode operator.
  Basic/Sum of Digits in A Number/solutionBySeema.cpp
Labels: hacktoberfest-accepted

#1286 Edit Distance -SolutionByArchit.cpp
  Dynamic Programming/Edit Distance/SolutionByArchit.cpp
Labels: hacktoberfest-accepted

#1283 calculate Factorial of a number
  Basic/Calculate Factorial of A Number/SolutionBySomya.py
Labels: hacktoberfest-accepted

#1281 Checking whether string is palindrome or not
  Basic/Check if A String is Palindrome or Not/SolutionBySomya.py
Labels: hacktoberfest-accepted

#1279 Create SolutionByVaishnavi.py
  Data Structure/Array Or Vector/Bubble Sort/SolutionByVaishnavi.py
Labels: hacktoberfest-accepted

#1277 Create SolutionByMukul.java
  Dynamic Programming/Max Sum Without Adjacent Element/SolutionByMukul.java
Labels: hacktoberfest-accepted

#1275 Create SolutionByMukul.java
  Dynamic Programming/Longest Common Prefix/SolutionByMukul.java
Labels: hacktoberfest-accepted

#1274 Create SolutionByMukul.java
  Dynamic Programming/Longest Increasing Subsequence/SolutionByMukul.java
Labels: hacktoberfest-accepted

#1270 Added Java Solution
  Divide and Conquer/K-th Element of Two Sorted Arrays/SolutionByDhanam.java
Labels: hacktoberfest-accepted

#1267 I have added user input in Quick Sort using Python 3
  Data Structure/Array Or Vector/Quick Sort/SolutionBySaksham.py
Labels: hacktoberfest-accepted

#1300 Binary to Decimal Program
  Basic/Convert Binary to Decimal/SolutinByIndra.java
Labels: hacktoberfest-accepted

#1299 Create SolutionByShrishti.cpp
  Bit Algorithm/Count Number of Set Bits in A Number/SolutionByShrishti.cpp
Labels: hacktoberfest-accepted

#1298 Create SolutionByShrishti.cpp
  Bit Algorithm/Find Non-Repeated Element/SolutionByShrishti.cpp
Labels: hacktoberfest-accepted

#1294 Resolved Compilation Error
  Dynamic Programming/Wildcard Pattern Matching/SolutionByRishi.java
Labels: hacktoberfest-accepted

#1296 Create SolutionByShrishti.cpp
  Data Structure/Array Or Vector/Trapping Rainwater Problem/SolutionByShrishti.cpp
Labels: hacktoberfest-accepted

#1295 Create SolutionByTanmay.cpp
  Data Structure/Matrix/Print A Given Matrix in Spiral Form/SolutionByTanmay.cpp
Labels: hacktoberfest-accepted

#1297 Create SolutionByShrishti.cpp
  Bit Algorithm/Check if A Number is Power of Two/SolutionByShrishti.cpp
Labels: hacktoberfest-accepted

#1289 MCM -SolutionByArchit.cpp
  Dynamic Programming/Matrix Chain Multiplication/SolutionByArchit.cpp
Labels: hacktoberfest-accepted

#1288 0-1 Knapsack -SolutionByArchit.cpp
  Dynamic Programming/0-1 Knapsack Problem/SolutionByArchit.cpp
Labels: hacktoberfest-accepted

#1285 Check Odd And Even Number
  Basic/Check Whether a Number is Even or Odd/SolutionBySomya.py
Labels: hacktoberfest-accepted

#1284 Checking number is prime or not
  Basic/Check if A Number is Prime or Not/SolutionBySomya.py
Labels: hacktoberfest-accepted

#1266 computed length of a string using STL.
  Basic/Check Whether a Number is Even or Odd/solutionBySeema.cpp
  Basic/Compute Length of A String/SolutionBySeema.cpp
Labels: hacktoberfest-accepted

#1076 Created Count smaller
  Data Structure/Array Or Vector/Count Smaller Elements On Right Side/SolutionByKuljeet.cpp
Labels: Working

#1092 Maximum Sum of K consecutive elements
  Data Structure/Array Or Vector/Maximum Sum Of K Consecutive elements/SolutionByKuljeet.cpp
  Data Structure/Array Or Vector/Maximum Sum Of K Consecutive elements/readMe.md
Labels: Working

#1123 Count Distinct elements in an Array
  Data Structure/Array Or Vector/Count Distinct elements in an Array/SolutionByKuljeet.cpp
  Data Structure/Array Or Vector/Count Distinct elements in an Array/readMe.md
Labels: Working

#1161 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Left View of A Binary Tree/SolutionbyRishabhSharma.java
Labels: Working

#1163 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Top View of Binary Tree/SolutionbyRishabhSharma.java
Labels: Working

#1278 count no of digits in an integer
  Basic/Check Whether a Number is Even or Odd/SolutionByShivam.py
  Basic/Count Number of Digits in An Integer/SolutionByShivam.py
Labels: hacktoberfest-accepted

#1258 odd even check
  Basic/Check Whether a Number is Even or Odd/SolutionByShivam.py
Labels: bug

#1171 added few programns
  Basic/Calculate Nth Fibonacci Number/SolutionByPrathamChoudhary.cpp
  Basic/Check if A String is Palindrome or Not/SolutionByPrathamChoudhary.cpp
Labels: hacktoberfest-accepted

#1164 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Print All Full Nodes/SolutionbyRishabhSharma.java
Labels: Working

#1167 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Vertical Sum in A Binary Tree/SolutionbyRishabhSharma.java
Labels: Working

#1306 Added Java Solution for DP Problem - Palindrome Partitioning
  Dynamic Programming/Palindrome Partitioning/solutionByMihirSood.java
Labels: hacktoberfest-accepted

#1307 Create SolutionByVaishnavi.py
  Data Structure/Array Or Vector/Insertion Sort/SolutionByVaishnavi.py
Labels: hacktoberfest-accepted

#1309 SolutionByVaishnavi.py
  Data Structure/Array Or Vector/Reverse of An Array/SolutionByVaishnavi.py
Labels: hacktoberfest-accepted

#1310 SolutionByVaishnavi.py
  Data Structure/Array Or Vector/Counting Sort/SolutionByVaishnavi.py
Labels: hacktoberfest-accepted

#1311 SolutionByVaishnavi.py
  Data Structure/Array Or Vector/Selection Sort/SolutionByVaishnavi.py
Labels: hacktoberfest-accepted

#1312 SolutionByVaishnavi.py
  Data Structure/Array Or Vector/Equilibrium Point in an Array/SolutionByVaishnavi.py
Labels: hacktoberfest-accepted

#1317 Create SolutionByVanshika.cpp
  Bit Algorithm/Find Two Non-Repeating Elements/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1318 Create SolutionDivya.java
  Data Structure/Array Or Vector/Sort An Array of 0s and 1s/SolutionDivya.java
Labels: hacktoberfest-accepted

#1324 Create SolutionByVanshika.cpp
  Bit Algorithm/Count Number of Set Bits in A Number/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1325 Create SolutionByAyaz.cpp
  Basic/Check Whether a Number is Even or Odd/SolutionByAyaz.cpp
Labels: hacktoberfest-accepted

#1329 SolutionbyRishabhSharma2.java
  Data Structure/Binary Tree/Diameter of Binary Tree/SolutionbyRishabhSharma2.java
Labels: hacktoberfest-accepted

#1330 Create SolutionBykhushi.cpp
  Data Structure/Stack/Stack Using Array/SolutionBykhushi.cpp
Labels: hacktoberfest-accepted

#1334 Create SolutionByVanshika.cpp
  Data Structure/Array Or Vector/Find Second Largest Number/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1331 Create SolutionBykhushi.cpp
  Data Structure/Stack/Stack Using Linked List/SolutionBykhushi.cpp
Labels: hacktoberfest-accepted

#1333 Create SolutionBykhushi.cpp
  Data Structure/Queue/Queue Using Linked List/SolutionBykhushi.cpp
Labels: hacktoberfest-accepted

#1332 Create SolutionBykhushi.cpp
  Data Structure/Queue/Queue Using Array/SolutionBykhushi.cpp
Labels: hacktoberfest-accepted

#1326 Binomial Coefficient - readMe
  Dynamic Programming/Binomial Coefficient/readMe.md
Labels: hacktoberfest-accepted

#1319 Create SolutionByVanshika.cpp
  Data Structure/Linked List/Reverse A Singly Linked List/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1323 Create SolutionByVanshika.cpp
  Data Structure/Stack/Parenthesis Checker/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1321 Create SolutionBykhushi.cpp
  Data Structure/Matrix/Multiplication of Two Matrices/SolutionBykhushi.cpp
Labels: hacktoberfest-accepted

#1354 Size of The Subarray With Maximum Sum - readMe
  Dynamic Programming/Size of The Subarray With Maximum Sum/readMe.md
Labels: hacktoberfest-accepted

#1351 Count Number of Ways to jump to Reach End - readMe
  Dynamic Programming/Count Number of Ways to jump to Reach End/readMe.md
Labels: hacktoberfest-accepted

#1335 Create SolutionByAyush.go
  Basic/Calculate Factorial of A Number/SolutionByAyush.go
Labels: hacktoberfest-accepted

#1346 Count Balanced Binary Trees of Height h - readMe
  Dynamic Programming/Count Balanced Binary Trees of Height H/readMe.md
Labels: hacktoberfest-accepted

#1353 Eulerian Number - readMe
  Dynamic Programming/Eulerian Number/readMe.md
Labels: hacktoberfest-accepted

#1352 Delannoy number - readMe
  Dynamic Programming/Delannoy number/readMe.md
Labels: hacktoberfest-accepted

#1350 Count Number of Subsets having Given XOR Value -readMe
  Dynamic Programming/Count Number of Subsets having Given XOR Value/readMe.md
Labels: hacktoberfest-accepted

#1349 Count Number of Increasing SubSequence - readMe
  Dynamic Programming/Count Number of Increasing SubSequence/readMe.md
Labels: hacktoberfest-accepted

#1348 Count Inversions - readMe
  Dynamic Programming/Count Inversions/readMe.md
Labels: hacktoberfest-accepted

#1347 Count Distinct Subsequences - readMe
  Dynamic Programming/Count Distinct Subsequences/readMe.md
Labels: hacktoberfest-accepted

#1345 Combinational Sum - readMe
  Dynamic Programming/Combinational Sum/readMe.md
Labels: hacktoberfest-accepted

#1336 Create SolutionByKriti.java
  Basic/Find GCD of Two Numbers/SolutionByKriti.java
Labels: hacktoberfest-accepted

#1338 Create SolutionByKriti.java
  Basic/Reverse A Given Number/SolutionByKriti.java
Labels: hacktoberfest-accepted

#1339 Create SolutionByVanshika.cpp
  Data Structure/Array Or Vector/Count Occurence of an element in a sorted arrray/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1340 Create SolutionByAadi.cpp
  Data Structure/Array Or Vector/Bubble Sort/SolutionByAadi.cpp
Labels: hacktoberfest-accepted

#1344 Perfect Sum DP based solution
  Dynamic Programming/Perfect Sum Problem/SolutionByKuljeet.cpp
Labels: hacktoberfest-accepted

#1355 Added uglyno using DP
  Dynamic Programming/Ugly Numbers/SolutionByJatin.cpp
Labels: hacktoberfest-accepted

#1357 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Vertical Order of Binary Tree/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1359 SolutionbyRishabhSharma.java
  Data Structure/Binary Tree/Level Order Traversal in Spiral Form/SolutionbyRishabhSharma.java
Labels: hacktoberfest-accepted

#1360 Added Files
  Bit Algorithm/Find Non-Repeated Element/SolutuonByAadi.cpp
Labels: hacktoberfest-accepted

#1358 Create SolutionbySparsh.cpp
  Basic/Check if A Number is Prime or Not/SolutionbySparsh.cpp
Labels: hacktoberfest-accepted

#1363 Create SolutionByDhanam.java
  Backtracking/Sudoku/SolutionByDhanam.java
Labels: hacktoberfest-accepted

#1322 Create SolutionByVanshika.cpp
  Data Structure/Linked List/Check if A Singly Linked List is Palindrome or Not/SolutionByVanshika.cpp
Labels: hacktoberfest-accepted

#1201 Closest Pair of numbers distance by divide and conquer
  Divide and Conquer/Closest Pair of Numbers Distance/SolutionByAnkita.cpp
  Divide and Conquer/Closest Pair of Numbers Distance/readMe.md
Labels: hacktoberfest-accepted

#1343 Added Solution
  Basic/Calculate Factorial of A Number/SolutionByAryan.cpp
  Divide and Conquer/Longest Common Prefix/SolutionByAryan.cpp
Labels: hacktoberfest-accepted

#1369 Create SolutionBySakshi.java
  Dynamic Programming/Wildcard Pattern Matching/SolutionBySakshi.java
Labels: hacktoberfest-accepted

#1364 Create SolutionByDhanam.java
  Backtracking/Rat in A Maze/SolutionByDhanam.java
Labels: hacktoberfest-accepted

#1365 Siva kumar2001 patch 3 1
  Basic/Find GCD of Two Numbers/SolutionBySivaKumar.cpp
Labels: hacktoberfest-accepted

#1370 added SolutionByUjjawal.cpp
  Data Structure/Array Or Vector/Arrange Given Numbers to Form the Biggest Number/SolutionByUjjawal.cpp
Labels: hacktoberfest-accepted

#1371 Nth Tribonacci number
  Basic/Calculate Nth Tribonacci Number/SolutionByAyush.go
Labels: hacktoberfest-accepted

#1372 Added Solution to Kth Smallest Problem
  Divide and Conquer/K-th Element of Two Sorted Arrays/SolutionByAryan.cpp
Labels: hacktoberfest-accepted

#1273 to determine whether a given year is leap year or not !
  Basic/Check Leap Year/solutionBySeema.cpp
Labels: hacktoberfest-accepted

#1276 Add Permutations of String in Java
  Backtracking/Permutations of A String/SolutionByRitikaJain.java
Labels: hacktoberfest-accepted

#1374 Permutations of A String - readMe
  Backtracking/Permutations of A String/readMe.md
Labels: hacktoberfest-accepted

#1375 Check Leap Year
  Basic/Check Leap Year/SolutionByAyush.go
Labels: hacktoberfest-accepted

#1377 Updated Contribution.md for Pushing New problems
  Contributing.md
Labels: hacktoberfest-accepted

#1388 DS File
  Greedy Algorithms/.DS_Store
Labels: hacktoberfest-accepted

#1389 Removed DS File
  Divide and Conquer/.DS_Store
Labels: hacktoberfest-accepted

#1381 Power Set using backtracking
  Backtracking/Power Set in Lexicographic Order/SolutionByManisha.cpp
Labels: hacktoberfest-accepted

#1380 using Backtracking
  Backtracking/Minimum Number of Jumps to Reach ( M , N ) From ( 1 , 1 )/SolutionByManisha.cpp
Labels: hacktoberfest-accepted

#1378 Factorial Solution in CPP
  Basic/Calculate Factorial of A Number/SolutionByManisha.cpp
Labels: hacktoberfest-accepted

#1379 Using Backtracking
  Backtracking/Combinational Sum/SolutionByManisha.cpp
Labels: hacktoberfest-accepted

#1367 SolutionByMashiyatHussain
  Data Structure/Array Or Vector/Selection Sort/SolutionbyMashiyatHussain.cpp
Labels: hacktoberfest-accepted

#1260 SolutionByAquib.py
  Basic/Compute Length of A String/SolutionByAquib.py
Labels: hacktoberfest-accepted
