Repository shoaibrayeen/Programmers-Community, pull requests merged in 2020-04, with the labels that each got.

#971 Create SolutionByRiya.py
  Greedy Algorithms/Activity Selection Problem/SolutionByRiya.py
Labels: Optimize it

#973 Create SolutionByRiya.py
  Greedy Algorithms/Fractional Knapsack Problem/SolutionByRiya.py
Labels: Optimize it

#916 Create SolutionByMananpreet.java
  Data Structure/Linked List/Detect Loop in Singly Linked List/SolutionByMananpreet.java
Labels: Working

#918 Create SolutionByMananpreet.java
  Data Structure/Linked List/Count Occurrence of A number in A Singly Linked List/SolutionByMananpreet.java
Labels: Working

#919 Create SolutionByMananpreet.java
  Data Structure/Linked List/Check if A Singly Linked List is Palindrome or Not/SolutionByMananpreet.java
Labels: Working

#920 Create SolutionByMananpreet.java
  Data Structure/Linked List/Find Length of Singly Linked List/SolutionByMananpreet.java
Labels: Working

#921 Create SolutionByMananpreet.java
  Data Structure/Linked List/Find Middle Element of The Singly Linked List/SolutionByMananpreet.java
Labels: Working

#924 Create SolutionByMananpreet.java
  Data Structure/Linked List/Insertion and Deletion in Linked List/SolutionByMananpreet.java
Labels: Working

#926 Create SolutionByMananpreet.java
  Data Structure/Linked List/Reverse A Singly Linked List/SolutionByMananpreet.java
Labels: Working

#967 Create SolutionByChanpreet3.java
  Data Structure/Linked List/Detect Loop in Singly Linked List/SolutionByChanpreet3.java
Labels: Working

#966 Create SolutionByMananpreet.java
  Data Structure/Matrix/Print A Given Matrix in Spiral Form/SolutionByMananpreet.java
Labels: Working

#965 Create SolutionByMananpreet.java
  Data Structure/Matrix/Subtraction of Two Matrices/SolutionByMananpreet.java
Labels: Working

#964 Create SolutionByMananpreet.java
  Data Structure/Matrix/Multiplication of Two Matrices/SolutionByMananpreet.java
Labels: Working

#963 Create SolutionByMananpreet.java
  Data Structure/Matrix/Addition of Two Matrices/SolutionByMananpreet.java
Labels: Working

#934 SolutionByRishabhSharma.cpp
  Data Structure/Linked List/Detect Loop in Singly Linked List/SolutionByRishabhSharma.cpp
Labels: In Review

#978 SolutionByRishabhSharma.cpp
  Basic/Convert Decimal To Binary/SolutionByRishabhSharma.cpp
Labels: In Review

#1007 SolutionByAbhay
  Basic/Convert Binary to Decimal/SolutionByAbhay.cpp
Labels: In Review

#968 Fixes and code
  Divide and Conquer/Median of Two Sorted Array/SolutionByXkcdjerry.c
  Divide and Conquer/Median of Two Sorted Array/readMe.md
Labels: In Review

#996 Create solutionbyPooja.cpp
  Data Structure/Binary Tree/Print All Full Nodes/solutionbyPooja.cpp
Labels: In Review
